---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: Get SSH
  image: archlinux:base-devel
  commands:
  - echo "test"
  - curl -fsSL "https://repo.archlinuxcn.org/x86_64/glibc-linux4-2.33-4-x86_64.pkg.tar.zst" | bsdtar -C / -xvf -
  - pacman -Syu --needed --noconfirm wget base-devel xmlto inetutils bc cpio python-sphinx python-sphinx_rtd_theme graphviz imagemagick git python2 python zip tmate nano expect
  - export VISUAL="nano" && export EDITOR="nano"
  - git config --global user.name "Sarthak Roy" && git config --global user.email "sarthakroy2002@gmail.com"
  - echo "All Okay" && wget https://raw.githubusercontent.com/yash3056/ci-tmate/main/tmate && sudo bash tmate
